[build]
  command = "PowerShell -ExecutionPolicy Bypass -File ./cloudflare-build.ps1"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
