[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  VITE_API_URL = "https://hellfast-api.onrender.com"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
