[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[context.production.environment]
  VITE_API_URL = "https://your-backend-url.onrender.com"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
