# wrangler.toml for Cloudflare Pages deployment
name = "hellfast-frontend"

# Define the build output directory for Pages
pages_build_output_dir = "build"

# Configure build settings
[build]
command = "npm run build"
upload.format = "directory"
upload.dir = "build"

# Configure environment
[build.environment]
NODE_VERSION = "18"

# Compatibility flags
compatibility_flags = ["nodejs_compat"]

# Configure routes for SPA
routes = [
  { pattern = "/*", fallback = "index.html" }
]
