name = "hellfast-frontend"
workers_dev = true

[build]
command = "cd frontend && npm install --legacy-peer-deps postcss-nesting && npm run build"

[site]
bucket = "./frontend/build"

[build.upload]
format = "directory"
dir = "./frontend/build"

[pages]
pages_build_output_dir = "frontend/build"
root_dir = "frontend"

compatibility_date = "2023-10-30"
