name = "hellfast-frontend"

# Use a more robust build approach that avoids package-lock issues
[build]
command = "cd frontend && npm install --no-package-lock && npm run build"

[site]
bucket = "./frontend/build"

# Configure build upload correctly
[build.upload]
format = "directory"
dir = "./frontend/build"

# Make sure to use exactly this property name for Pages integration
[pages]
pages_build_output_dir = "frontend/build"
root_dir = "frontend"

compatibility_date = "2023-10-30"
