name = "hellfast-frontend"

[build]
command = "cd frontend && npm install --legacy-peer-deps && npm run build"

[site]
bucket = "./frontend/build"

[build.upload]
format = "directory"
main = "./frontend/build/index.html"
dir = "./frontend/build"

[pages]
build_output_dir = "frontend/build"
