name: hellfast-app
services:
- name: web
  github:
    repo: your-github-username/hellfast
    branch: main
  # Force Python 3.10 which has better compatibility with packages
  environment_slug: python
  build_command: |
    echo "Using Python version:"
    python --version
    python -m pip install --upgrade pip
    
    # Install PyYAML with binary option first to prevent build issues
    pip install --no-binary :all: PyYAML==6.0
    
    # Then install remaining requirements
    pip install -r requirements.txt
    
    # Frontend build
    cd frontend && npm ci && npm run build
  run_command: python main.py
  envs:
  - key: APP_ENV
    value: production
    scope: RUN_AND_BUILD_TIME
  - key: FRONTEND_URL
    value: ${APP_URL}
    scope: RUN_AND_BUILD_TIME
  - key: PADDLE_SANDBOX
    value: "false"
    scope: RUN_TIME
  - key: PORT
    value: "8000"
    scope: RUN_AND_BUILD_TIME
  - key: PYTHON_VERSION
    value: "3.10"
    scope: RUN_AND_BUILD_TIME
  routes:
  - path: /
    preserve_path_prefix: true
  http_port: 8000
